// Tests the distribution generated by Java's Math.random() function.

import org.w3c.dom.ranges.Range;

public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		int greaterCount = 0;
		int lessCount = 0;
		for (int i = 0; i < N; i++){
			if (Math.random() > 0.5){
				greaterCount = greaterCount + 1;
			}
			else{
				lessCount = lessCount + 1;
			}
		}
		System.out.println("> 0.5: " + greaterCount + "\n" + "<= 0.5: " + lessCount);
		if (lessCount != 0){
			System.out.println((double) greaterCount / lessCount);
		}
	}
}